spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: zpj523123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos的地址，不要加http
        server-addr: localhost:8848
        #执行集群名称
        cluster-name: BJ
    sentinel:
      transport:
        #指定sentinel的控制台地址
        dashboard: localhost:8080
  application:
    name: house
server:
  port: 9003
mybatis-plus:
  mapper-locations: classpath*:/house/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
